### ISSUE TITLE
Use react hooks

### ISSUE THREAD

**Issue by Kamahl19** [Kamahl19/react-starter#13]
Rewrite classes to stateless components using hooks

**Comment by MiroslavPetrik** [comment]
Started work on this in https://github.com/Kamahl19/react-starter/pull/71
and https://github.com/Kamahl19/react-starter/pull/70
which were super simple.

Do we want to drop all the classes?

**Comment by Kamahl19** [comment]
yep why not :) lets take a red pill :D i will take this so i get familiar with it as well
