### ISSUE TITLE
Discussion: Sidebar 

### ISSUE THREAD

**Issue by abhishekp21** [Kamahl19/react-starter#1508]
@Kamahl19, are there any intentions to introduce a sidebar drawer that supports both horizontal and vertical navbar configurations? It would be beneficial if the sidebar could be customized to switch between a compact version and a full-sized version.

Just attaching some screenshot

![Screenshot 2024-02-01 at 1 07 21 PM](https://github.com/Kamahl19/react-starter/assets/18423249/a13eb4dc-7673-4108-9f6e-5b0116578bff)

![Screenshot 2024-02-01 at 1 07 15 PM](https://github.com/Kamahl19/react-starter/assets/18423249/b0da406d-09ba-4fa2-85d7-dccacd00c27b)

**Comment by Kamahl19** [comment]
This projects should server just as a starter. You can easily use shadcnui or any other library and add the sidebar to your own application. Previously this starter included the "dashboard layout" using the Ant Design library but in the meantime I switched to Tailwind and ShadcnUI and used much simpler layout.

**Comment by Kamahl19** [comment]
@abhishekp21 you can also easily add Sidebar from https://tailwindui.com/components/application-ui/application-shells/sidebar
