### ISSUE TITLE
Cleanup common/components

### ISSUE THREAD

**Issue by Kamahl19** [Kamahl19/react-starter#20]
https://github.com/Kamahl19/react-starter/blob/07c63691bb7fb12d8cc74658bc06cf6d32e5b3b6/src/common/components/index.js#L1

Remove all unused reexported components we dont really use

**Comment by MiroslavPetrik** [comment]
We actually use all the components. Nothing to do here.

I have one question though - when a components import a sibling, do we want to import it like
`import { Sibling } from '../'` - used in `GlobalSpinner`
or
`import Sibling from '../Sibling' - used in `Header`

Also we are not exporting all custom non-ant components e.g. Logo, Navbar, GlobalSpinner from the `components/index`. Those are only 2 tasks remaining in the `common/components` folder.
