### ISSUE TITLE
Make login route accept redirect path.

### ISSUE THREAD

**Issue by MiroslavPetrik** [Kamahl19/react-starter#310]
Often when you are logged out, or are entering from link, you want to be redirected to some specific page instead of the default one.

Make the `login` route accept `redirect` param so you can do

`/login?redirect=profile`

**Comment by Kamahl19** [comment]
this is already implemented by redux-auth-wrapper although it's buggy. this `http://localhost:3000/auth/login?redirect=a/b/c` will redirect you to `http://localhost:3000/auth/a/b/c` instead of `http://localhost:3000/a/b/c`

**Comment by Kamahl19** [comment]
i tested it properly and it actually works just fine
