### ISSUE TITLE
Projects keeping up with the starter

### ISSUE THREAD

**Issue by MiroslavPetrik** [Kamahl19/react-starter#322]
Let's say you have multiple projects based on the starter. How do you keep up with new features and changes?

As it's not a package, whats left is to add this repo as second origin to the project and then cherry pick the commits you are behind.

In theory it's easy, in practice it can happen that you will have some merge conflicts, like when the route definition changed.

To keep the merge conflicts close to 0, we can restructure the app a bit, so when the 'core' changes, it does not affect the app code.

That way, you can easily move ahead few existing projects sharing the starter code.

**Comment by Kamahl19** [comment]
What exactly would you propose? 

Once we separate packages from application code properly, i dont think it will be an issue. All the application code that stays in starter is subjected to change in real world app. You may not need an auth, or you may want to have completly different header, layout etc. Or you maybe replace ant with material. Its easy to do these changes. You may follow the starter repo and cherry pick changes that suite your real world project or you may make the change manually in your project inspired by change in starter

**Comment by MiroslavPetrik** [comment]
yeah, but there is logic which I don't want to touch in every projeect and expect it to work & i would like to receive patches if some bug/logic flaw is found.

Like in the
- store config, relogin, lift gate
- storybook configs
- guards

Probably as it is it's ok, it's not much to resolve the occasional merge conflicts. We can close this

**Comment by Kamahl19** [comment]
I agree with you so if you have an idea how to restructure the code, let me know. I am open to this change for sure. 

Imho we would have to rewrite this into a framework but that might change this pretty simple starter into a hard to maintain hard to use project if not done correctly
