### ISSUE TITLE
Storybook improvements

### ISSUE THREAD

**Issue by MiroslavPetrik** [Kamahl19/react-starter#37]
Component driven development

- [x] add config to read `*.stories.js` files from https://www.learnstorybook.com/react/en/simple-component/ so we don't have to import them manually
- [x] move stories to the component folders
- [x] remove unused storybook addons

Addons
- [x] knobs https://github.com/storybooks/storybook/tree/master/addons/knobs
- [x] viewport https://github.com/storybooks/storybook/tree/master/addons/viewport
- [x] extract our custom addons to packages
- [x] remove unused custom addons

**Comment by MiroslavPetrik** [comment]
This issue is too large, some features are for later releases. 

It can't be targeted by PR.

We should always split and label properly. E.g. not mix bugs with ideas with future features

**Comment by Kamahl19** [comment]
@MiroslavPetrik i agree, please split into a new issue what you didnt do in the PR
