### ISSUE TITLE
Component structure

### ISSUE THREAD

**Issue by MiroslavPetrik** [Kamahl19/react-starter#38]
Each component should be in its folder with following files and contents

- [ ] index.js - logic, connecting to store, redux
- [ ] component.js - JSX component
- [ ] stories.js - stories of the component for various prop combinations (ideally exhaustive)
- [ ] test.js - jest unit test for logic, e.g. initial state in forms, asserting layout changes after some events etc.

**Comment by Kamahl19** [comment]
@MiroslavPetrik i think we should rename the component to `view.js` and stories to `story.js` (test is also singular, even though there is more tests)

**Comment by MiroslavPetrik** [comment]
Makes sense, will do
