### ISSUE TITLE
Replace axios

### ISSUE THREAD

**Issue by MiroslavPetrik** [Kamahl19/react-starter#425]
https://www.reddit.com/r/reactjs/comments/dcte0e/psa_axios_is_mostly_dead/

https://github.com/axios/axios/issues/1965

**Comment by Kamahl19** [comment]
@MiroslavPetrik do you have a better alternative? I am not against replacing axios if there is a good simple to use alternative with similarly powerful api

**Comment by Kamahl19** [comment]
i am thinking either https://github.com/sindresorhus/ky or https://github.com/elbywan/wretch could be a good replacement
