### ISSUE TITLE
Jest Tests

### ISSUE THREAD

**Issue by Kamahl19** [Kamahl19/react-starter#50]
We need to tests for:

Packages:
- [ ] admin-layout
- [ ] spinner

Application code:
- [ ] store
- [ ] common components
- [ ] user service
- [ ] api service
- [ ] i18next service
- [ ] rules
- [ ] auth feature

We should also update docs
- [ ] mention `yarn test` in README

https://jestjs.io/docs/en/getting-started
https://testing-library.com/docs/react-testing-library/intro
https://react-testing-examples.com/
https://github.com/kentcdodds/react-testing-library-course

**Comment by MiroslavPetrik** [comment]
We should have the monorepo before, so running jest does not include running all the package tests too...
