### ISSUE TITLE
Github Actions - show bundle size in PR

### ISSUE THREAD

**Issue by Kamahl19** [Kamahl19/react-starter#516]
Run `yarn analyze` and print bundle size and diff from `master` for each PR so that we know if certain change increases bundle size significantly.

**Comment by MiroslavPetrik** [comment]
Bundle size doesnt matter. Its ok to ship megabytes. Maybe a bit controversial statement but time to interaction is important for web pages not much for apps. This is low priority task.

**Comment by Kamahl19** [comment]
This is a general-purpose starter, we dont know what apps/webpages will be built with it. Also bundle size matters even more for mobile usage. You dont want to build an app which loads 10 seconds on Edge connection :)

**Comment by Kamahl19** [comment]
There is no such action right now and creating it is out of scope for this project. I will reevaluate in the future.
