### ISSUE TITLE
Update i18next

### ISSUE THREAD

**Issue by Kamahl19** [Kamahl19/react-starter#7]
- refactor i18next configuration
- use new i18next package with new api and components
- async load
- use i18next scanner
- use `<Trans />` everywhere in JSX

**Comment by MiroslavPetrik** [comment]
https://www.npmjs.com/package/react-i18next

https://www.npmjs.com/search?q=i18next

**Comment by MiroslavPetrik** [comment]
@Kamahl19 <Trans /> cannot be used solely as we need plain strings in placeholder
