### ISSUE TITLE
Router service with helpers and shared logic

### ISSUE THREAD

**Issue by MiroslavPetrik** [Kamahl19/react-starter#83]
It would be handy to have folder for router service from where we could import helpers.

- we could export configured reducer from there
https://github.com/Kamahl19/react-starter/blob/4dd1a251ebdbc06a4e792facf05a980356666d58/src/app/store/rootReducer.js#L12

- we could have location selectors there e.g. for `isActive('/some/path')`

- we could have helper hooks there like

`useHistoryChange(callback)`

```
import { useEffect } from 'react'
import { history }  from './configureStore'

export default function useHistoryChange(cb) {
  useEffect(() => history.listen(cb), []);
}
```

**Comment by Kamahl19** [comment]
i agree, lets include it into v3

**Comment by Kamahl19** [comment]
@MiroslavPetrik could you identify all possible things we could move there beside those you already pointed out? are there any other?

**Comment by MiroslavPetrik** [comment]
saga for location change

```
function* locationChanged({ payload }) {
  const activatePath = '/auth/activate/';

  if (payload.location.pathname.includes(activatePath)) {
    const exclude = activatePath.split('/');
    const [userId, activationToken] = payload.location.pathname
      .split('/')
      .filter(part => !exclude.includes(part));

    yield call(activateUser, userId, activationToken);
  }
}

// ...
yield takeEvery('@@router/LOCATION_CHANGE', locationChanged);

```

we should have
```
takeEvery(routerEnter("/auth/activate"), activateUser)
```
instead.

other like `routerLeave` could be handy.

**Comment by Kamahl19** [comment]
We already use a `use-react-router` which gives us a hook to get router and watch for location changes
