### ISSUE TITLE
Transform to monorepo

### ISSUE THREAD

**Issue by Kamahl19** [Kamahl19/react-starter#9]
- [ ] transform the repo to monorepo
- [ ] release all `/packages` as scoped npm packages (possibly use https://github.com/palmerhq/tsdx or https://github.com/bitjson/typescript-starter)
- [ ] https://github.com/facebook/create-react-app/blob/master/lerna.json
- [ ] https://github.com/facebook/create-react-app/blob/master/package.json
- [ ] yarn workspaces

**Comment by MiroslavPetrik** [comment]
Any plan on how to do this?

**Comment by MiroslavPetrik** [comment]
Looking forward to see this happen.
