### ISSUE TITLE
Routes config

### ISSUE THREAD

**Issue by Kamahl19** [Kamahl19/react-starter#92]
we need to create a mapof routes where we define paths instead of using stinrg everywhere in the app. We could even create a config where guards would be specified. Needs to be tested, maybe too much unnecessary abstraction and simple map of constants will be enough

**Comment by MiroslavPetrik** [comment]
We could have route constant for each feature? Not sure. Could be somewhat similar as reducer key to the store?

globalReducer - reducer key
globalRoutes - route key

route constants could be used in router-related sagas mentioned in https://github.com/Kamahl19/react-starter/issues/83 
here is a package for integration (route and saga) https://github.com/jfairbank/redux-saga-router
that requires route keys, which we should export from ducks... but that again goes beyond ducks spec.
